# Site
title: 'appx online'
author: Mr.X
favicon: assets/favicon/favicon.ico
logo: assets/logo.png
avatar: https://img.vim-cn.com/47/4b71c2326821a0565b04db27065a149aff0de2.png

language:
- en
- zh-CN
- zh-HK
- zh-TW
# timezone:
email: me@xaoxuu.com
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
root_domain: xaoxuu.com
url: https://appx.online
root: /
# permalink: :year/:month/:day/:title/
permalink: :title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: README.md

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
auto_spacing: true
titlecase: true # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 1 # 把文件名称转换为 (1) 小写或 (2) 大写	默认(0)
render_drafts: false
post_asset_folder: false
relative_link: false
future: false
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: "    "
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -updated

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: 'YYYY-MM-DD'
time_format: HH:mm:ss

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: material-x

# theme_cdn: true

# 全局导入
import:
  meta:
  - "<meta name='theme-color' content='#FFFFFF'>"
  - "<meta name='msapplication-TileColor' content='#1BC3FB'>"
  - "<meta name='msapplication-config' content='assets/favicon/browserconfig.xml'>"
  link:
  - "<link rel='shortcut icon' type='image/x-icon' href='assets/favicon/favicon.ico'>"
  - "<link rel='icon' type='image/x-icon' sizes='32x32' href='assets/favicon/favicon-32x32.png'>"
  - "<link rel='mask-icon' color='#1BC3FB' href='assets/favicon/safari-pinned-tab.svg'>"
  - "<link rel='manifest' href='assets/favicon/site.webmanifest'>"
  # script:

# ====================================================================== SEO优化
# sitemap
sitemap:
  path: sitemap.xml
  tag: false
  category: false

nofollow:
  enable: true
  exclude:
  - xaoxuu.com

# ====================================================================== 加载速度优化
# 图片懒加载
lazyload:
  enable: true
  onlypost: false
  loadingImg:

# all_minifier: true

# autoprefixer
autoprefixer:
  exclude:
  - '*.min.css'
  # remove: false # prevent autoprefixer remove page-break-inside
  # browsers:
  #   - 'last 2 versions'
  #   - '> 5%'


# ======================================================================  评论

# 评论
# disqus_shortname: xaoxuu
# livere_uid:
# valine
leancloud:
  app_id: dAAL3f8phzeu8bQ1BgR7zuXJ-gzGzoHsz
  app_key: tjn8iSu12Y18cJMtSD5oTR1z

# feed
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:

# ====================================================================== key

# Generator json content
jsonContent:
  meta: false
  keywords: false
  pages:
    title: true
    slug: false
    date: false
    updated: false
    comments: false
    path: false
    link: false
    permalink: true
    excerpt: false
    keywords: false
    text: true
    raw: false
    content: false
  posts:
    title: true
    slug: false
    date: false
    updated: false
    comments: false
    path: false
    link: false
    permalink: true
    excerpt: false
    keywords: false
    text: true
    raw: false
    content: false
    categories: false
    tags: false


# Deployment
## Docs: https://hexo.io/docs/deployment.html
# npm install hexo-deployer-git --save
deploy:
- type: git
  repo: https://github.com/appx-online/appx.online.git
  branch: gh-pages
  message: update
